### PR TITLE
Added parent parameter to bulk indexer

### PR DESCRIPTION
**Pull request by donnanicolas**
Just added the possibility of passing the parent to the bulk indexer

### CODE REVIEW

**Comment by arypurnomoz** [comment]
+1

**Comment by cognusion** [comment]
+1

**Comment by donnanicolas** [comment]
Any updates on this??

**Comment by mattbaird** [comment]
can you rebase the PR?

**Comment by donnanicolas** [comment]
Rebase'd
Thanks

**Comment by donnanicolas** [comment]
Need a new rebase?? I really need this, sorry to bother

**Comment by nimajalali** [comment]
Any updates on merging this? I could use it as well.

**Comment by weberr13** [comment]
I'm investigating this now, I will merge when I verify on my system.

**Comment by weberr13** [comment]
This one breaks tests.  I will see if I can get it working in a quick add on PR:

$ go test ./...
?   	github.com/mattbaird/elastigo	[no test files]
# github.com/mattbaird/elastigo/lib_test
# github.com/mattbaird/elastigo/lib_test
lib/coreexample_test.go:27: not enough arguments in call to indexer.Index
lib/coreexample_test.go:48: not enough arguments in call to indexer.Index
FAIL	github.com/mattbaird/elastigo/lib [build failed]
?   	github.com/mattbaird/elastigo/tutorial	[no test files]

**Pull request merged**
