### PR TITLE
Do not attempt to parse non json errors

### PR DESCRIPTION
**Pull request by maraino**
### Description
When elasticsearch is being used behind a proxy like nginx and it is not able to get a valid response from elasticsearch on time or it has problems to connect, nginx or any other proxy usually return html errors instead of JSON.

To avoid long, and not clear errors we can check the `Content-Type` and just return the status code as the error instead of the current long and unparseable error.

### CODE REVIEW

**Comment by vrecan** [comment]
could you add a test for this?

**Comment by vrecan** [comment]
I would merge this if it had tests.

**Comment by maraino** [comment]
@vrecan: Tests added and merged with mattbaird:master

**Comment by vrecan** [comment]
:+1:  thanks!

**Pull request merged**
