### PR TITLE
Add DynamicTemplates to MappingOptions

### PR DESCRIPTION
**Pull request by Gfif**
https://www.elastic.co/guide/en/elasticsearch/guide/master/custom-dynamic-mapping.html

### CODE REVIEW

**Comment by mattbaird** [comment]
can this be tested?

**Comment by weberr13** [comment]
@Gfif, Please update /lib/indicesputmapping_test.go with some tests for this and I will review and merge

**Comment by Gfif** [comment]
@weberr13 I've update my fork and add tests. Please review and merge.

**Comment by weberr13** [comment]
@Gfif. Thanks

**Pull request merged**
