### PR TITLE
Add support for multi-match queries in the dsl

### PR DESCRIPTION
**Pull request by kytrinyx**
This lets you search for a single term against multiple fields:

```
elastigo.Query().MultiMatch("fish", []string{"title", "description"}) 
```

### CODE REVIEW

**Comment by mattbaird** [comment]
did you mean to PR these? ;)

**Comment by kytrinyx** [comment]
I did :) Finally!

**Comment by kytrinyx** [comment]
I've got one more, too, if these go in.

**Comment by mattbaird** [comment]
excellent. Congrats on the new gig.

**Pull request merged**
